from frames.slide_frame import SlideFrame
from frames.terminal_frame import EmbeddedShell
from frames.output_frame import OutputFrame
from frames.storing_data_frame import StoringDataFrame
from frames.data_types_frame import DataTypesFrame
from frames.converting_types_frame import ConvertingTypesFrame
